export enum ActionType {
  FETCH_STANDING = 'fetch_standing',
  FETCH_STANDING_SUCCESS = 'fetch_standing_success',
  FETCH_STANDING_ERROR = 'fetch_standing_error',
  FETCH_SCHEDULE = 'fetch_schedule',
  FETCH_SCHEDULE_SUCCESS = 'fetch_schedule_success',
  FETCH_SCHEDULE_ERROR = 'fetch_schedule_error',
  FETCH_WIKIDATA = 'fetch_wikidata',
  FETCH_WIKIDATA_SUCCESS = 'fetch_wikidata_success',
  FETCH_WIKIDATA_ERROR = 'fetch_wikidata_error',
  FETCH_RESULT = 'fetch_result',
  FETCH_RESULT_SUCCESS = 'fetch_result_success',
  FETCH_RESULT_ERROR = 'fetch_result_error',
  FETCH_DRIVER = 'fetch_driver',
  FETCH_DRIVER_SUCCESS = 'fetch_driver_success',
  FETCH_DRIVER_ERROR = 'fetch_driver_error',
  SELECT_WEEKEND = 'select_weekend',
  SELECT_DRIVER = 'select_driver',
  OPEN_POPUP = 'open_popup',
  CLOSE_POPUP = 'close_popup',
}
