export enum ActionType {
  FETCH_STANDING = 'fetch_standing',
  FETCH_STANDING_SUCCESS = 'fetch_standing_success',
  FETCH_STANDING_ERROR = 'fetch_standing_error',
  FETCH_SCHEDULE = 'fetch_schedule',
  FETCH_SCHEDULE_SUCCESS = 'fetch_schedule_success',
  FETCH_SCHEDULE_ERROR = 'fetch_schedule_error',
  FETCH_RESULT = 'fetch_result',
  FETCH_RESULT_SUCCESS = 'fetch_result_success',
  FETCH_RESULT_ERROR = 'fetch_result_error',
  FETCH_WIKI_IMAGE = 'fetch_wiki_image',
  FETCH_WIKI_IMAGE_SUCCESS = 'fetch_wiki_image_success',
  FETCH_DRIVERINFO = 'fetch_driverinfo',
  SELECT_WEEKEND = 'select_weekend',
  SELECT_DRIVER = 'select_driver',
  OPEN_POPUP = 'open_popup',
  CLOSE_POPUP = 'close_popup',
}
