export enum ActionType {
  FETCH_STANDING = 'fetch_standing',
  FETCH_STANDING_SUCCESS = 'fetch_standing_success',
  FETCH_STANDING_ERROR = 'fetch_standing_error',
  FETCH_SCHEDULE = 'fetch_schedule',
  FETCH_SCHEDULE_SUCCESS = 'fetch_schedule_success',
  FETCH_SCHEDULE_ERROR = 'fetch_schedule_error',
  FETCH_RESULT = 'fetch_result',
  FETCH_RESULT_RACE = 'fetch_result_race',
  FETCH_RESULT_QUALIFY = 'fetch_result_qualify',
  FETCH_RESULT_ERROR = 'fetch_result_error',
  FETCH_WIKI_IMAGE = 'fetch_wiki_image',
  FETCH_WIKI_IMAGE_SUCCESS = 'fetch_wiki_image_success',
  FETCH_DRIVERINFO = 'fetch_driverinfo',
  FETCH_DRIVERINFO_SUCCESS = 'fetch_driverinfo_success',
  FETCH_DRIVERINFO_ERROR = 'fetch_driverinfo_error',
  FETCH_SEASONS = 'fetch_seasons',
  SELECT_WEEKEND = 'select_weekend',
  SELECT_DRIVER = 'select_driver',
  SELECT_DROPDOWN_OPTION = 'select_dropdown_option',
  OPEN_POPUP = 'open_popup',
  CLOSE_POPUP = 'close_popup',
  OPEN_ERROR_POPUP = 'open_error_popup',
  CLOSE_ERROR_POPUP = 'close_error_popup',
}
